### DISCUSSION TITLE
Sandpack v2 with `environment: 'node'` - how to remove the vite status iframe?

### DISCUSSION THREAD

**Discussion by nirtamir2** [codesandbox/sandpack#734] [Q&A] [answered]
I tried sandpack v2 with vite template. But I notice there is a bottom status bar for vite with the loading status and after it loads in shows text showing vite dev server port.
How to remove them? 
I try doing it via css
```css

            .sp-bridge-frame {
              display: none; 
            }
            
            .sp-c-cRHAdc {
              display: none; 
            }
           
```

![image](https://user-images.githubusercontent.com/16452789/220079862-d01f96c6-7d07-455e-abea-6aa2b06cd6b2.png)

![image](https://user-images.githubusercontent.com/16452789/220079874-d178965b-02f9-45df-9280-acacc982bc37.png)

But where selecting `.sp-bridge-frame` class seems ok , the `  .sp-c-cRHAdc` for the loading details seems like an unstable HACK. Is there a better way to remove them?
